INSERT INTO Materia (id, nombre)
    VALUES (1, N'Alemán'),
           (2, N'Álgebra'),
           (3, N'Análisis Matemático'),
           (4, N'Base de Datos'),
           (5, N'Economía'),
           (6, N'Filosofía'),
           (7, N'Frances'),
           (8, N'Física'),
           (9, N'Geografía'),
           (10, N'Historia'),
           (11, N'Inglés'),
           (12, N'Italiano'),
           (13, N'Lengua'),
           (14, N'Matemática'),
           (15, N'Probabilidad y Estadística'),
           (16, N'Programación'),
           (17, N'Psicología'),
           (18, N'Química'),
           (19, N'Otra');