INSERT INTO Institucion (id, nombre)
    VALUES (1, N'N/A'),
           (2, N'Instituto Tecnológico de Buenos Aires'),
           (3, N'Universidad Abierta Interamericana'),
           (4, N'Universidad Argentina de la Empresa'),
           (5, N'Universidad Argentina John F. Kennedy'),
           (6, N'Universidad Austral'),
           (7, N'Universidad Católica Argentina'),
           (8, N'Universidad de Buenos Aires'),
           (9, N'Universidad de Morón'),
           (10, N'Universidad de Palermo'),
           (11, N'Universidad de San Andrés'),
           (12, N'Universidad del Salvador'),
           (13, N'Universidad Nacional de Catamarca'),
           (14, N'Universidad Nacional de Córdoba'),
           (15, N'Universidad Nacional de Entre Ríos'),
           (16, N'Universidad Nacional de Formosa'),
           (17, N'Universidad Nacional de Jujuy'),
           (18, N'Universidad Nacional de La Matanza'),
           (19, N'Universidad Nacional de La Pampa'),
           (20, N'Universidad Nacional de la Patagonia Austral'),
           (21, N'Universidad Nacional de La Plata'),
           (22, N'Universidad Nacional de La Rioja'),
           (23, N'Universidad Nacional de Lanús'),
           (24, N'Universidad Nacional de Lomas de Zamora'),
           (25, N'Universidad Nacional de Luján'),
           (26, N'Universidad Nacional de Misiones'),
           (27, N'Universidad Nacional de Moreno'),
           (28, N'Universidad Nacional de Quilmes'),
           (29, N'Universidad Nacional de Rio Negro'),
           (30, N'Universidad Nacional de Rosario'),
           (31, N'Universidad Nacional de Río Cuarto'),
           (32, N'Universidad Nacional de Salta'),
           (33, N'Universidad Nacional de San Juan'),
           (34, N'Universidad Nacional de Santiago del Estero'),
           (35, N'Universidad Nacional de Tierra del Fuego'),
           (36, N'Universidad Nacional de Tucumán'),
           (37, N'Universidad Tecnológica Nacional'),
           (38, N'Otra');