INSERT INTO Carrera (id, nombre)
    VALUES (1, N'N/A'),
           (2, N'Administración y Sistemas'),
           (3, N'Análisis de sistemas'),
           (4, N'Arquitectura'),
           (5, N'Bioquímica'),
           (6, N'Biotecnología'),
           (7, N'Ciencias biológicas'),
           (8, N'Ciencias Físicas'),
           (9, N'Ciencias Matemáticas'),
           (10, N'Ciencias Químicas'),
           (11, N'Contador Público'),
           (12, N'Diseño Gráfico'),
           (13, N'Diseño Industrial'),
           (14, N'Diseño Web'),
           (15, N'Economía'),
           (16, N'Ingeniería Civil'),
           (17, N'Ingeniería de Alimentos'),
           (18, N'Ingeniería Electricista'),
           (19, N'Ingeniería Electrónica'),
           (20, N'Ingeniería en Informática'),
           (21, N'Ingeniería en Alimentos'),
           (22, N'Ingeniería Mecánica'),
           (23, N'Ingeniería Química'),
           (24, N'Letras'),
           (25, N'Medicina'),
           (26, N'Nutrición'),
           (27, N'Programador de Sistemas'),
           (28, N'Psicología'),
           (29, N'Psicología Social'),
           (30, N'Sociología'),
           (32, N'Tecnicatura en Desarrollo Web'),
           (33, N'Tecnicatura en Desarrollo de Aplicaciones Móviles'),
           (34, N'Otra');